version: "3.8"

services:
    alice:
        image: quay.io/curl/curl:latest
        container_name: alice
        mac_address: 02:42:ac:1f:00:02
        restart: always
        entrypoint: sleep infinity
        networks:
          mitm:
            ipv4_address: 172.31.0.2
    bob:
        image: python:latest
        container_name: bob
        mac_address: 02:42:ac:1f:00:03
        restart: always
        volumes:
            - ./bob:/var/www
        working_dir: /var/www
        networks:
          mitm:
            ipv4_address: 172.31.0.3
        entrypoint: python -m http.server 80
    mallory:
        cap_add:
          - NET_ADMIN
        build: .
        container_name: mallory
        mac_address: 02:42:ac:1f:00:04
        entrypoint: sleep infinity
        volumes:
            - ./src:/data
        sysctls:
            - net.ipv4.ip_forward=1
            - net.ipv6.conf.all.forwarding=1
            - net.ipv4.conf.all.send_redirects=0
        networks:
          mitm:
            ipv4_address: 172.31.0.4

networks:
  mitm:
    internal: true
    ipam:
      config:
        - subnet: 172.31.0.0/24